### ISSUE TITLE
Add more comments to hammerspoon-init.lua?

### ISSUE THREAD

**Issue by niyazpk** [derekwyatt/dotfiles#2]
Hello,

Was looking at your `hammerspoon-init.lua` file to see how I can replace `ShiftIt` with `Hammerspoon`. Would be really nice if you can add a few comments around the features so that it is clear what you are trying to do. (Since this file is linked from the ShiftIt readme file, I think a lot of people will be interested in this file).

Thanks a bunch for open-sourcing this code!

**Comment by derekwyatt** [comment]
Good idea. Done in commit 3d0887a25bfb75c471f5fc647e47264d25bbe714.

**Comment by niyazpk** [comment]
Awesome. Thanks!
